AWSTemplateFormatVersion: '2010-09-09'
Description: An Amazon S3 trigger that retrieves metadata for the object that has
  been updated.
Parameters:
  BucketName:
    Description: Name of S3 bucket for lambda trigger
    Type: String
  CPU:
    Default: '50'
    Description: CPU for task definition
    Type: String
  ContainerName:
    Description: Name of service
    Type: String
  ECSCluster:
    Description: ECS Cluster
    Type: String
  Image:
    Description: Docker image repository
    Type: String
  Memory:
    Default: '150'
    Description: Memory for task definition
    Type: String
  ServiceName:
    Description: Name of service
    Type: String
  TaskRoleArn:
    Description: Task Role ARN for lambda function
    Type: String
  TaskSubnets:
    Default: ''
    Description: Subnet IDs to launch fargate task
    Type: List<AWS::EC2::Subnet::Id>
Resources:
  Bucket1:
    Properties:
      BucketName:
        Ref: BucketName
    Type: AWS::S3::Bucket
  CloudwatchLogsGroup:
    Properties:
      LogGroupName:
        Fn::Join:
        - '-'
        - - Ref: ServiceName
          - Ref: AWS::StackName
      RetentionInDays: 14
    Type: AWS::Logs::LogGroup
  ECSServiceRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - ecs.amazonaws.com
      Path: /
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - elasticloadbalancing:DeregisterInstancesFromLoadBalancer
            - elasticloadbalancing:DeregisterTargets
            - elasticloadbalancing:Describe*
            - elasticloadbalancing:RegisterInstancesWithLoadBalancer
            - elasticloadbalancing:RegisterTargets
            - ec2:Describe*
            - ec2:AuthorizeSecurityGroupIngress
            Effect: Allow
            Resource: '*'
        PolicyName: ecs-service
    Type: AWS::IAM::Role
  s3getobject:
    Properties:
      CodeUri: s3://lambda.bucket.moodle/19fdeae6b17f57ab61f95415d65b9c6d
      Description: An Amazon S3 trigger that retrieves metadata for the object that
        has been updated.
      Environment:
        Variables:
          CLUSTER:
            Ref: ECSCluster
          SUBNETS:
            Ref: TaskSubnets
          TASK_DEFINITION:
            Ref: taskdefinition
          TASK_ROLE_ARN:
            Ref: TaskRoleArn
      Events:
        BucketEvent1:
          Properties:
            Bucket:
              Ref: Bucket1
            Events:
            - s3:ObjectCreated:*
          Type: S3
      Handler: index.handler
      MemorySize: 128
      Policies:
      - Statement:
        - Action:
          - s3:GetObject
          Effect: Allow
          Resource: arn:aws:s3:::*
        Version: '2012-10-17'
      Runtime: nodejs6.10
      Timeout: 3
    Type: AWS::Serverless::Function
  service:
    Properties:
      Cluster:
        Ref: ECSCluster
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 0
      DesiredCount: '1'
      LaunchType: FARGATE
      Role:
        Ref: ECSServiceRole
      ServiceName:
        Ref: ServiceName
      TaskDefinition:
        Ref: taskdefinition
    Type: AWS::ECS::Service
  taskdefinition:
    Properties:
      ContainerDefinitions:
      - Cpu:
          Ref: CPU
        Essential: 'true'
        Image:
          Ref: Image
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-group:
              Ref: CloudwatchLogsGroup
            awslogs-region:
              Ref: AWS::Region
        Memory:
          Ref: Memory
        Name:
          Ref: ContainerName
      Family:
        Fn::Join:
        - ''
        - - Ref: AWS::StackName
          - Ref: ContainerName
      NetworkMode: awsvpc
    Type: AWS::ECS::TaskDefinition
Transform: AWS::Serverless-2016-10-31
