version: 2
jobs:
  build:
    docker:
      - image: larse514/circle-ci-node-docker:latest
    environment:
      - DEPLOY_BUCKET: "lambda.bucket.moodle"
      - BUCKET_NAME: "project.feedme.rds.scripts"
      - APP_NAME: "RDSLoader-ci"
      - CLUSTER: "batch-cluster"
      - IMAGE: "larse514/rds-loader:16"
      - SUBNET1: "subnet-6dae5f27"
      - SUBNET2: "subnet-1d042940"
      - SG: "sg-8f4238c6"
      - TASK_ROLE_ARN: "arn:aws:iam::417615409974:role/RDS-Loader-Task-Role"
    working_directory: ~/fargate-batch-runner/trigger
    steps:
      - checkout
    #   - run:
    #       name: update-npm
    #       command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: |
            npm install && ls && pwd
          
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: code-coverage
          command: 'npm run test'
      - run: 
          working_directory: ~/fargate-batch-runner
          name: deploy
          command: |
            ./deploy.sh ${DEPLOY_BUCKET} ${APP_NAME} ${BUCKET_NAME} \
            ${APP_NAME} ${APP_NAME} ${CLUSTER} ${IMAGE} ${TASK_ROLE_ARN} \
            ${SUBNET1} ${SUBNET2} ${SG}
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml