version: 2
jobs:
  build:
    docker:
      - image: larse514/circle-ci-node-docker:latest
    environment:
      - DEPLOY_BUCKET: "cloudformation-bucket-community-alliance"
      - TRIGGER_BUCKET: "community.alliance.batch.runner.trigger"
      - TRIGGER_BUCKET_CI: "community.alliance.batch.runner.ci.trigger"
      - TRIGGER: "./trigger/trigger.txt"
      - TRIGGER_FILE_NAME: "trigger.txt"
      - NEW_BUCKET: "dummyfargatebatchrunnerbucket"
      - NEW_BUCKET_REGION: "us-east-1"
      - APP_NAME_CI: "RDSLoader-ci-test"
      - APP_NAME: "RDSLoader-test"
      - CLUSTER: "community-alliance-dev-cluster"
      - IMAGE: "larse514/fargate-batch-runner-test-container:latest"
      - SUBNET1: "subnet-03d0996a110b0df80"
      - SUBNET2: "subnet-01dae19f56f192a37"
      - SG: "sg-0fe06144cc7a0ae94"
      - ROLE_STACK_CI: "testrolestack"
      - ROLE_STACK: "batch-runner-stack"
    steps:
      - checkout
    #   - run:
    #       name: update-npm
    #       command: 'sudo npm install -g npm@latest'
      # - restore_cache:
      #     key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: |
            cd trigger && npm install 
          
      # - save_cache:
      #     key: dependency-cache-{{ checksum "package.json" }}
      #     paths:
      #       - ./trigger/node_modules
      - run:
          name: unit test
          command: 'cd trigger && npm run test'
      - run: 
          name: Configure AWS environment
          command: |
            aws configure set default.region us-east-1
            aws configure set default.output json
      - run: 
          name: test batch trigger
          command: |
            #just cd into the directory because i don't want to read the circleci docs anymore =/
            cd test
            ./deploy.sh ${DEPLOY_BUCKET} ${APP_NAME_CI} ${TRIGGER_BUCKET_CI} \
            ${APP_NAME_CI} ${APP_NAME_CI} ${CLUSTER} ${IMAGE}  \
            ${SUBNET1} ${SUBNET2} ${SG}
            #test the s3 trigger
            ./test-s3-trigger.sh ${TRIGGER_BUCKET_CI} ${TRIGGER_FILE_NAME} ${TRIGGER} ${NEW_BUCKET} ${NEW_BUCKET_REGION}

            #cleanup
            ./cleanup.sh ${ROLE_STACK_CI} ${NEW_BUCKET} ${APP_NAME_CI}
      - run: 
          name: deploy
          command: |
            #just cd into the directory because i don't want to read the circleci docs anymore =/
            cd test
            ./deploy.sh ${DEPLOY_BUCKET} ${APP_NAME} ${TRIGGER_BUCKET} \
            ${APP_NAME} ${APP_NAME} ${CLUSTER} ${IMAGE}  \
            ${SUBNET1} ${SUBNET2} ${SG}
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml